version: "3"

services:
  redis:
    build: ./redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
  mongo:
    build: ./mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
